name: AutoMakeXRSYS
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  makexrsys:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        makeversion: 
          - w1124h264
          - w1123h264
          - w1022h264
          - w11lt2464
          - w10lt2164
          - w10lt1964
          - w10lt1664
        isosd: 
          - true
          - false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get rclone Config
        uses: actions/checkout@v4
        with:
          repository: xrgzs/rclone-action
          token: ${{ secrets.RCLONE_TOKEN }}
          path: bin

      - name: Change DNS Server
        shell: pwsh
        run: |
          $newDnsServers = @('1.1.1.1', '8.8.8.8')
          $networkAdapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
          foreach ($adapter in $networkAdapters) {
              Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ResetServerAddresses
              Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses $newDnsServers
          }
          ipconfig /flushdns

      - name: Big Task
        shell: pwsh
        run: |
          $makeversion = [string] "${{ matrix.makeversion }}"
          $isosd       = [bool] $${{ matrix.isosd }}
          .\makexrsys.ps1
